export const apiData = {
  title: 'Music catalog API',
  description: 'Music catalog with authors and their compositions',
  version: '1.0',
  tag: 'Music catalog',
  helloWorld: 'Hello World!',
  authorTag: 'author',
  compositionTag: 'composition',
  createComposition: 'Create composition',
  findCompositions: 'Find all compositions',
  findFilteredCompositions: 'Find compositions filtered by title/author/genre',
  findComposition: 'Find composition',
  updateComposition: 'Update composition',
  deleteComposition: 'Delete composition',
  createAuthor: 'Create author',
  findAuthors: 'Find all authors',
  findFilteredAuthors: 'Find authors filtered by name',
  findCompositionsByAuthor: 'Find compositions by author',
  findAuthor: 'Find author',
  updateAuthor: 'Update author',
  deleteAuthor: 'Delete author',
  authorName: 'Author name',
  authorLink: 'Link to author site',
  compositionTitle: 'Composition title',
  authorId: 'Author id',
  compositionDuration: 'Composition duration in sec',
  compositionGenre: 'Composition genre',
};
